/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo, useContext, createContext, useEffect } from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { FrontSide } from 'three'
const context = createContext()
export function TavernInstances({ children, ...props }) {
  const { nodes } = useGLTF('models/tavern.glb')
  const instances = useMemo(
    () => ({
      CadeiraStainlessSteelSatin: nodes['Cadeira_1_Stainless_Steel_-_Satin_0001'],
      CadeiraPaintEnamelGlossyRed1: nodes['Cadeira_2_(1)_Paint_-_Enamel_Glossy_(Red)_0001'],
      CadeiraStainlessSteelBrushedLinearLong:
        nodes['Cadeira_3_Stainless_Steel_-_Brushed_Linear_Long_0001'],
      MesaStainlessSteelSatin: nodes['Mesa_2_(3)_Stainless_Steel_-_Satin_0001'],
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Tavern(props) {
  const instances = useContext(context)
  const { nodes, materials } = useGLTF('models/tavern.glb')
  useEffect(() => {
    for (const key in materials) {
      materials[key].side = FrontSide
    }
  })
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Baqueta_(1)_Plastic_-_Translucent_Glossy_(Yellow)_0001'].geometry}
        material={materials['Plastic_-_Translucent_Glossy_Yellow.001']}
        position={[-22.34906578, 0.16896039, 0.74278373]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Baqueta (1)_Plastic - Translucent Glossy (Yellow)_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Baqueta_(2)_Banqueta_Carvalho_-_Semibrilhante_0001'].geometry}
        material={materials['Banqueta_Carvalho_-_Semibrilhante.001']}
        position={[-22.34906578, 0.16896039, 0.74278373]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Baqueta (2)_Banqueta Carvalho - Semibrilhante_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Aro_de_metal_(1)_(2)_Coating_-_Black_Oxide_0001'].geometry}
        material={materials['Coating_-_Black_Oxide.001']}
        position={[-20.51301003, -0.6953609, -3.79985857]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Aro de metal (1) (2)_Coating - Black Oxide_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Ba��_(2)_Barris_Nogueira_0001'].geometry}
        material={materials['Barris_Nogueira.001']}
        position={[-20.51301003, -0.6953609, -3.79985857]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Ba�� (2)_Barris Nogueira_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cartaz_1_cartaz_2_Poliestireno_0001.geometry}
        material={materials['cartaz_2_Poliestireno.001']}
        position={[-22.34908676, 0, 0.75940174]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Cartaz 1_cartaz 2 Poliestireno_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cartaz_2_cartaz_Espelho_0001.geometry}
        material={materials['cartaz_Espelho.001']}
        position={[-22.34908676, 0, 0.75940174]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Cartaz 2_cartaz Espelho_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Machado_(1)_Nickel_-_Polished_0001'].geometry}
        material={materials['Nickel_-_Polished.001']}
        position={[-22.34908676, 0, 0.7427839]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Machado (1)_Nickel - Polished_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Machado_Nickel_-_Satin_0001'].geometry}
        material={materials['Nickel_-_Satin.001']}
        position={[-22.34908676, 0, 0.7427839]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Machado_Nickel - Satin_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Cadeira_1_Paint_-_Enamel_Glossy_(Red)_0001'].geometry}
        material={materials['Paint_-_Enamel_Glossy_Red.001']}
        position={[-18.50370979, -0.04445966, -12.0860815]}
        rotation={[-Math.PI, 0.73151344, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949588]}
        userData={{ name: 'Cadeira 1_Paint - Enamel Glossy (Red)_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Cadeira_2_Plastic_-_Translucent_Glossy_(Blue)_0001'].geometry}
        material={materials['Plastic_-_Translucent_Glossy_Blue.001']}
        position={[-18.50370979, -0.04445966, -12.0860815]}
        rotation={[-Math.PI, 0.73151344, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949588]}
        userData={{ name: 'Cadeira 2_Plastic - Translucent Glossy (Blue)_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cadeira_3_Mesa_redonda_Mogno_0001.geometry}
        material={materials['Mesa_redonda_Mogno.001']}
        position={[-18.50370979, -0.04445966, -12.0860815]}
        rotation={[-Math.PI, 0.73151344, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949588]}
        userData={{ name: 'Cadeira 3_Mesa redonda Mogno_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cadeira_4_PEEK_0001.geometry}
        material={materials['PEEK.001']}
        position={[-18.50370979, -0.04445966, -12.0860815]}
        rotation={[-Math.PI, 0.73151344, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949588]}
        userData={{ name: 'Cadeira 4_PEEK_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Moldura_quadro_Carbon_Fiber_-_Plain_0001'].geometry}
        material={materials['Carbon_Fiber_-_Plain.001']}
        position={[-22.34908676, 0, 0.7427839]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Moldura quadro_Carbon Fiber - Plain_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Pano_de_prato_Fabric_(Light_Brown)_0001'].geometry}
        material={materials['Fabric_Light_Brown_0.001']}
        position={[-22.34908676, 0, 0.7427839]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Pano de prato_Fabric (Light Brown)_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Acabamento_1_Deta��hes_de_madeiraas_Cerejeira_0001'].geometry}
        material={materials['Detahes_de_madeiraas_Cerejeira.001']}
        position={[-22.34887505, 0.00054293, 0.74527234]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00959083, 0.00949587]}
        userData={{ name: 'Acabamento 1_Deta��hes de madeiraas Cerejeira_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Balc��o_(1)_Balc��o_Pintura_-_Esmalte_com_brilho_(C'].geometry}
        material={materials['Balco_Pintura_-_Esmalte_com_brilho_Cinza_escuro.001']}
        position={[-22.34887505, 0.00054293, 0.74527234]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Balc��o (1)_Balc��o Pintura - Esmalte com brilho (C' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['chamin��_Polymide_(Kapton)_0001'].geometry}
        material={materials['Polymide_Kapton.001']}
        position={[-22.76669502, 0.00054293, 0.74527234]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.0096858, 0.00949587, 0.00948637]}
        userData={{ name: 'chamin��_Polymide (Kapton)_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Detalhe_Balc��o_(1)_Bronze_-_Patina_0001'].geometry}
        material={materials['Bronze_-_Patina.001']}
        position={[-22.34887505, 0.00054293, 0.74527234]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Detalhe Balc��o (1)_Bronze - Patina_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Escada_Pine_0001.geometry}
        material={materials['Pine.001']}
        position={[-22.34887505, 0.00054293, 0.74527234]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Escada_Pine_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Fogueira_Lenha_Bambu_claro_-_Semi-brilhante_0001'].geometry}
        material={materials['Lenha_Bambu_claro_-_Semi-brilhante.001']}
        position={[-22.34887505, 0.00054293, 0.74527234]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Fogueira_Lenha Bambu claro - Semi-brilhante_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Iterno_da_lareira_PA_11_-_Nylon-_HP_11-30_(with_EOS_P_396_3'].geometry}
        material={materials['PA_11_-_Nylon-_HP_11-30_with_EOS_P_396_3D_Printer.001']}
        position={[-22.13996696, 0.09550162, 0.74527228]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00940092, 0.00921099, 0.00930595]}
        userData={{ name: 'Iterno da lareira_PA 11 - Nylon- HP 11-30 (with EOS P 396 3' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Janela_(1)_Gemstone_-_Ruby_0001'].geometry}
        material={materials['Gemstone_-_Ruby.001']}
        position={[-22.34887505, 0.00054293, 0.74527234]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Janela (1)_Gemstone - Ruby_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Lareira_Lareira_Superf��cie_-_Fosca_0001'].geometry}
        material={materials['Lareira_Superfcie_-_Fosca.001']}
        position={[-22.34887505, 0.00054293, 0.74527234]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00940091]}
        userData={{ name: 'Lareira_Lareira Superf��cie - Fosca_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Lenha_Fabric_(Light_Brown)_0001'].geometry}
        material={materials['Fabric_Light_Brown.001']}
        position={[-22.34887505, 0.00054293, 0.74527234]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Lenha_Fabric (Light Brown)_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Parede_1_Parede_Superf��cie_-_Fosca_0001'].geometry}
        material={materials['Parede_Superfcie_-_Fosca.001']}
        position={[-22.34887505, 0.00054293, 0.74527234]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Parede 1_Parede Superf��cie - Fosca_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Piso_Surface_-_Matte_0001'].geometry}
        material={materials['Surface_-_Matte.001']}
        position={[-22.34887505, 0.00054293, 0.74527234]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Piso_Surface - Matte_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Porta_da_Escada_(1)_Gemstone_-_Diamond_0001'].geometry}
        material={materials['Gemstone_-_Diamond.001']}
        position={[-22.34887505, 0.00054293, 0.74527234]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Porta da Escada (1)_Gemstone - Diamond_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Porta_da_Escada_Gemstone_-_Sapphire_0001'].geometry}
        material={materials['Gemstone_-_Sapphire.001']}
        position={[-22.34887505, 0.00054293, 0.74527234]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Porta da Escada_Gemstone - Sapphire_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Prateleiras_Estante_Pintura_-_Esmalte_com_brilho_(Verde)_0001'].geometry}
        material={materials['Estante_Pintura_-_Esmalte_com_brilho_Verde.001']}
        position={[-22.34887505, 0.00054293, 0.74527234]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Prateleiras_Estante Pintura - Esmalte com brilho (Verde)_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Puxador_(1)_Steel_-_Satin_0001'].geometry}
        material={materials['Steel_-_Satin.001']}
        position={[-22.34887505, 0.00054293, 0.74527234]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Puxador (1)_Steel - Satin_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Tampo_Balc��o_Paek_(Beige)_0001'].geometry}
        material={materials['Paek_Beige.001']}
        position={[-22.34887505, 0.00054293, 0.74527234]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Tampo Balc��o_Paek (Beige)_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Vidro_(1)_Glass_(Clear)_0001'].geometry}
        material={materials['Glass_Clear.001']}
        position={[-22.34887505, 0.00054293, 0.74527234]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Vidro (1)_Glass (Clear)_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Pilar_(1)_Cherry_0001'].geometry}
        material={materials['Cherry.001']}
        position={[-22.34906578, 0, 0.74278378]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Pilar (1)_Cherry_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Quadro_Paper_(White)_0001'].geometry}
        material={materials['Paper_White.001']}
        position={[-22.34908676, 0, 0.75940174]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Quadro_Paper (White)_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Body13_LED_(Red)_0001'].geometry}
        material={materials['LED_Red.001']}
        position={[-22.34906578, 0, 0.74278378]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Body13_LED (Red)_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Tocha_(1)_(2)_tocha_Pal��dio_-_Polido_0001'].geometry}
        material={materials['tocha_Paldio_-_Polido.001']}
        position={[-22.34906578, 0, 0.74278378]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Tocha (1) (2)_tocha Pal��dio - Polido_0.001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Vela_(1)_(2)_Nylon_6-6_(White)_0001'].geometry}
        material={materials['Nylon_6-6_White.001']}
        position={[-22.34906578, 0, 0.74278378]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.00949588, 0.00949587, 0.00949587]}
        userData={{ name: 'Vela (1) (2)_Nylon 6-6 (White)_0.001' }}
      />
      <group userData={{ name: 'Node_37' }}>
        <instances.CadeiraStainlessSteelSatin
          position={[3.80434966, -0.04153367, -20.62057495]}
          rotation={[0, 1.57053468, 0]}
          scale={[0.00949587, 0.00949587, 0.00949588]}
          userData={{ name: 'Cadeira 1_Stainless Steel - Satin_0.001' }}
        />
        <instances.CadeiraStainlessSteelSatin
          position={[-23.3565197, -0.04153373, -2.47258472]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.00949588, 0.00949587, 0.00949587]}
          userData={{ name: 'Cadeira 1_Stainless Steel - Satin_0.002' }}
        />
      </group>
      <group userData={{ name: 'Node_38' }}>
        <instances.CadeiraPaintEnamelGlossyRed1
          position={[3.80434966, -0.04153367, -20.62057495]}
          rotation={[0, 1.57053468, 0]}
          scale={[0.00949587, 0.00949587, 0.00949588]}
          userData={{ name: 'Cadeira 2 (1)_Paint - Enamel Glossy (Red)_0.001' }}
        />
        <instances.CadeiraPaintEnamelGlossyRed1
          position={[-23.3565197, -0.04153373, -2.47258472]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.00949588, 0.00949587, 0.00949587]}
          userData={{ name: 'Cadeira 2 (1)_Paint - Enamel Glossy (Red)_0.002' }}
        />
      </group>
      <group userData={{ name: 'Node_39' }}>
        <instances.CadeiraStainlessSteelBrushedLinearLong
          position={[3.80434966, -0.04153367, -20.62057495]}
          rotation={[0, 1.57053468, 0]}
          scale={[0.00949587, 0.00949587, 0.00949588]}
          userData={{ name: 'Cadeira 3_Stainless Steel - Brushed Linear Long_0.001' }}
        />
        <instances.CadeiraStainlessSteelBrushedLinearLong
          position={[-23.3565197, -0.04153373, -2.47258472]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.00949588, 0.00949587, 0.00949587]}
          userData={{ name: 'Cadeira 3_Stainless Steel - Brushed Linear Long_0.002' }}
        />
      </group>
      <group userData={{ name: 'Node_40' }}>
        <instances.MesaStainlessSteelSatin
          position={[3.80435038, -0.04153371, -20.62058258]}
          rotation={[0, 1.57053468, 0]}
          scale={[0.00949587, 0.00949587, 0.00949588]}
          userData={{ name: 'Mesa 2 (3)_Stainless Steel - Satin_0.001' }}
        />
        <instances.MesaStainlessSteelSatin
          position={[-23.35652733, -0.04153373, -2.47258496]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.00949588, 0.00949587, 0.00949587]}
          userData={{ name: 'Mesa 2 (3)_Stainless Steel - Satin_0.002' }}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/tavern.glb')


