/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 test.glb -p -E 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/test.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box002_ORANGE_0.geometry} material={materials.Atlas} position={[2.367, 3.582, 122.974]} scale={[346.477, 207.364, 136.021]} />
    </group>
  )
}

useGLTF.preload('/test.glb')
