/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 test.glb -p -E 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/test.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box002_ORANGE_0.geometry} material={materials.Atlas} position={[-29.474, 42.98, -58.969]} rotation={[-Math.PI / 2, 0, 0]} scale={[219.325, 140.484, 42.414]} />
    </group>
  )
}

useGLTF.preload('/test.glb')
